name: suwayomi

services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:v2.1.1922
    user: $PUID:$PGID
    container_name: suwayomi
    restart: unless-stopped
    expose:
      - 80
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      
      # Port settings
      BIND_IP: 0.0.0.0
      BIND_PORT: 80
      
      # Authentication settings - Simple Login method
      AUTH_MODE: ui_login
      AUTH_USERNAME: admin
      AUTH_PASSWORD: $default_pwd
      
      # Download settings
      DOWNLOAD_AS_CBZ: true

      # Extension repository (Keiyoushi only)
      EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'

      # FlareSolverr integration
      FLARESOLVERR_ENABLED: true
      FLARESOLVERR_URL: http://suwayomi-flaresolverr:8191

      WEB_UI_UPDATE_INTERVAL: 0 # Disable automatic update checks - updates are managed via Docker

      AUTO_DOWNLOAD_CHAPTERS : true # Enable auto-download of new chapters for followed manga

    volumes: # The order matters! Make sure the downloads is first in the volume list or it will not work!
      - /DATA/Media/Mangas/:/home/suwayomi/.local/share/Tachidesk/downloads
      - /DATA/AppData/suwayomi/data/:/home/suwayomi/.local/share/Tachidesk
    depends_on:
      - flaresolverr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: suwayomi-flaresolverr
    restart: unless-stopped
    user: 0:0
    environment:
      TZ: $TZ

x-casaos:

  main: suwayomi
  index: /
  webui_port: 80

  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Suwayomi/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Suwayomi/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Suwayomi/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Suwayomi/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/Suwayomi/screenshot-1.png

  architectures:
    - amd64
    - arm64
  author: Yundera Team
  category: Media
  description:
    en_us: |
      **Read manga like Netflix for comics**
      
      Suwayomi lets you read thousands of manga (Japanese comics) from around the world, all in one place. Instead of visiting dozens of different websites or losing track of where you left off, everything is organized in one beautiful app.
      
      **What you can do:**
      • Read manga on your phone, tablet, or computer
      • Automatically keeps track of what you've read
      • Download chapters to read offline (great for commutes!)
      • Works with popular manga apps you already use
      
      **Think of it like:** A personal library that automatically organizes all your favorite comics and remembers exactly where you stopped reading.
      
      **Perfect if you:** Love reading manga, want to keep track of multiple series, or get frustrated when manga websites go down or change.
    ko_kr: |
      **만화를 위한 넷플릭스처럼 읽기**
      
      스와요미는 전 세계 수천 개의 만화를 한 곳에서 읽을 수 있게 해줍니다. 수십 개의 다른 웹사이트를 방문하거나 어디까지 읽었는지 잊어버리는 대신, 모든 것이 하나의 아름다운 앱에서 정리됩니다.
      
      **할 수 있는 것:**
      • 휴대폰, 태블릿, 컴퓨터에서 만화 읽기
      • 읽은 내용을 자동으로 기록
      • 오프라인으로 읽기 위해 챕터 다운로드 (통근할 때 좋아요!)
      • 이미 사용 중인 인기 만화 앱과 연동
      
      **이렇게 생각해보세요:** 좋아하는 모든 만화를 자동으로 정리하고 정확히 어디서 읽기를 멈췄는지 기억하는 개인 도서관.
      
      **이런 분께 완벽해요:** 만화를 좋아하고, 여러 시리즈를 추적하고 싶거나, 만화 웹사이트가 다운되거나 변경될 때 짜증나는 분들.
    zh_cn: |
      **像Netflix一样阅读漫画**
      
      Suwayomi让您在一个地方阅读来自世界各地的数千部漫画。不再需要访问数十个不同的网站或忘记读到哪里，所有内容都在一个美观的应用中整理。
      
      **您可以做的事:**
      • 在手机、平板或电脑上阅读漫画
      • 自动跟踪您的阅读进度
      • 下载章节离线阅读（通勤时很棒！）
      • 与您已使用的热门漫画应用配合使用
      
      **可以这样想:** 一个自动整理所有喜爱漫画并准确记住您停止阅读位置的个人图书馆。
      
      **非常适合:** 喜欢阅读漫画、想要跟踪多个系列或因漫画网站宕机或更改而感到沮丧的人。
    fr_fr: |
      **Lire des mangas comme Netflix pour les bandes dessinées**
      
      Suwayomi vous permet de lire des milliers de mangas du monde entier, tout en un seul endroit. Au lieu de visiter des dizaines de sites web différents ou de perdre le fil de votre lecture, tout est organisé dans une belle application.
      
      **Ce que vous pouvez faire :**
      • Lire des mangas sur votre téléphone, tablette ou ordinateur
      • Suit automatiquement ce que vous avez lu
      • Télécharger des chapitres pour lire hors ligne (parfait pour les trajets !)
      • Fonctionne avec les applications manga populaires que vous utilisez déjà
      
      **Pensez-y comme :** Une bibliothèque personnelle qui organise automatiquement tous vos mangas favoris et se souvient exactement où vous avez arrêté de lire.
      
      **Parfait si vous :** Aimez lire des mangas, voulez suivre plusieurs séries, ou êtes frustré quand les sites de manga tombent en panne ou changent.
    es_es: |
      **Lee manga como Netflix para cómics**
      
      Suwayomi te permite leer miles de mangas de todo el mundo, todo en un solo lugar. En lugar de visitar docenas de sitios web diferentes o perder la pista de dónde lo dejaste, todo está organizado en una hermosa aplicación.
      
      **Lo que puedes hacer:**
      • Leer manga en tu teléfono, tablet o computadora
      • Automáticamente lleva registro de lo que has leído
      • Descargar capítulos para leer sin conexión (¡genial para viajes!)
      • Funciona con aplicaciones de manga populares que ya usas
      
      **Piénsalo como:** Una biblioteca personal que organiza automáticamente todos tus cómics favoritos y recuerda exactamente dónde dejaste de leer.
      
      **Perfecto si:** Amas leer manga, quieres seguir múltiples series, o te frustras cuando los sitios de manga se caen o cambian.
  developer: Suwayomi Project
  tagline:
    en_us: Your personal manga library with 1200+ sources
    ko_kr: 1200개 이상의 소스를 가진 개인 만화 라이브러리
    zh_cn: 拥有1200+源的个人漫画图书馆
    fr_fr: Votre bibliothèque manga personnelle avec plus de 1200 sources
    es_es: Tu biblioteca personal de manga con más de 1200 fuentes
  title:
    en_us: Suwayomi
  tips:
    before_install:
      en_us: |
        **Getting Started**
        | Username | Password       |
        | -------- | -------------- |
        | `admin`  | `$default_pwd` |
        
        **How to use:**
        1. Open the website in your browser
        2. Login with the username and password above
        3. Click "Browse" to find manga sources
        4. Search for your favorite manga titles
        5. Start reading! Your progress saves automatically

      ko_kr: |
        **시작하기**
        | 사용자명 | 비밀번호       |
        | -------- | -------------- |
        | `admin`  | `$default_pwd` |
        
        **사용 방법:**
        1. 브라우저에서 웹사이트 열기
        2. 위의 사용자명과 비밀번호로 로그인
        3. "찾아보기"를 클릭하여 만화 소스 찾기
        4. 좋아하는 만화 제목 검색
        5. 읽기 시작! 진행 상황이 자동으로 저장됩니다
        
        **찾을 수 있는 인기 만화:**
        원피스, 나루토, 진격의 거인, 귀멸의 칼날 등 전 세계 사이트에서 수천 개 더.
        
        **팁:** WiFi에서 챕터를 다운로드한 후 통근 중에 오프라인으로 읽어보세요!
      zh_cn: |
        **开始使用**
        | 用户名   | 密码           |
        | -------- | -------------- |
        | `admin`  | `$default_pwd` |
        
        **使用方法:**
        1. 在浏览器中打开网站
        2. 使用上述用户名和密码登录
        3. 点击"浏览"查找漫画源
        4. 搜索您喜爱的漫画标题
        5. 开始阅读！您的进度会自动保存
        
        **您可以找到的热门漫画:**
        海贼王、火影忍者、进击的巨人、鬼灭之刃，以及来自世界各地网站的数千部作品。
        
        **提示:** 在WiFi下下载章节，然后在通勤时离线阅读！
      fr_fr: |
        **Commencer**
        | Nom d'utilisateur | Mot de passe   |
        | ----------------- | -------------- |
        | `admin`           | `$default_pwd` |
        
        **Comment utiliser:**
        1. Ouvrez le site web dans votre navigateur
        2. Connectez-vous avec le nom d'utilisateur et mot de passe ci-dessus
        3. Cliquez sur "Parcourir" pour trouver des sources de manga
        4. Recherchez vos titres de manga favoris
        5. Commencez à lire ! Votre progression se sauvegarde automatiquement
        
        **Mangas populaires que vous pouvez trouver:**
        One Piece, Naruto, L'Attaque des Titans, Demon Slayer, et des milliers d'autres de sites du monde entier.
        
        **Astuce:** Téléchargez les chapitres en WiFi, puis lisez hors ligne pendant les trajets !
      es_es: |
        **Comenzar**
        | Usuario  | Contraseña     |
        | -------- | -------------- |
        | `admin`  | `$default_pwd` |
        
        **Cómo usar:**
        1. Abre el sitio web en tu navegador
        2. Inicia sesión con el usuario y contraseña de arriba
        3. Haz clic en "Explorar" para encontrar fuentes de manga
        4. Busca tus títulos de manga favoritos
        5. ¡Comienza a leer! Tu progreso se guarda automáticamente
        
        **Manga popular que puedes encontrar:**
        One Piece, Naruto, Ataque a los Titanes, Demon Slayer, y miles más de sitios de todo el mundo.
        
        **Consejo:** ¡Descarga capítulos en WiFi, luego lee sin conexión durante viajes!