name: stirlingpdf

services:
  stirling-pdf:
    container_name: Stirling-PDF
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/ | grep -qv 'Please sign in'"]
      interval: 5s
      timeout: 10s
      retries: 16
    volumes:
      - /DATA/AppData/$AppID/stirling/data:/usr/share/tessdata:rw
      - /DATA/AppData/$AppID/stirling/config:/configs:rw
      - /DATA/AppData/$AppID/stirling/logs:/logs:rw
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      SECURITY_ENABLELOGIN: "false"
      LANGS: "en_GB,en_US,ar_AR,de_DE,fr_FR,es_ES,zh_CN,zh_TW,ca_CA,it_IT,sv_SE,pl_PL,ro_RO,ko_KR,pt_BR,ru_RU,el_GR,hi_IN,hu_HU,tr_TR,id_ID"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: Stirling-PDF
      UI_HOMEDESCRIPTION: Demo site for Stirling-PDF Latest
      UI_APPNAMENAVBAR: Stirling-PDF Latest
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "true"
      SHOW_SURVEY: "true"
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  port_map: "8080"
  description:
    en_us: Stirling-PDF is an open-source local web-based tool that allows you to easily edit, convert, merge and split PDF files.
    zh_cn: Stirling-PDF 是一个开源的本地网页工具，可以让您轻松地编辑、转换、合并和分割PDF文件。
    ko_kr: Stirling-PDF는 PDF 파일을 쉽게 편집, 변환, 병합, 분할할 수 있는 오픈소스 로컬 웹 기반 도구입니다.
  icon: https://raw.githubusercontent.com/BookJJun-IJ/AppStore/create/Apps/Stirling-PDF/icons.png
  screenshot_link:
    - https://raw.githubusercontent.com/BookJJun-IJ/AppStore/create/Apps/Stirling-PDF/screenshots1.png
    - https://raw.githubusercontent.com/BookJJun-IJ/AppStore/create/Apps/Stirling-PDF/screenshots2.png
    - https://raw.githubusercontent.com/BookJJun-IJ/AppStore/create/Apps/Stirling-PDF/screenshots3.png
  tagline:
    en_us: PDF editing, conversion, and management in one open-source local tool
    zh_cn: 用于编辑、转换和管理PDF文件的开源本地工具
    ko_kr: PDF 파일 편집, 변환, 관리를 위한 오픈소스 로컬 도구
  index: /
  title: 
    en_us: Stirling - PDF
    zh_cn: Stirling - PDF
    ko_kr: Stirling - PDF
  is_uncontrolled: false
  category: office
  volumes:
    - /DATA/AppData/$AppID/stirling/data
    - /DATA/AppData/$AppID/stirling/config
    - /DATA/AppData/$AppID/stirling/logs