name: tailscale

services:
  tailscale:
    image: ghcr.io/tailscale/tailscale:v1.86.5
    container_name: tailscale-node
    hostname: tailscale-casaos
    user: $PUID:$PGID  # Userspace mode doesn't require root
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    environment:
      - TZ=$TZ
      - TS_AUTHKEY=${TS_AUTHKEY:-}
      - TS_HOSTNAME=casaos-${HOSTNAME:-server}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--webclient --accept-routes --advertise-exit-node
      - TS_USERSPACE=true
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - /DATA/AppData/tailscale/state:/var/lib/tailscale
      - /DATA/AppData/tailscale/config:/config
    expose:
      - 80  # Web UI port
    ports:
      - "41641:41641/udp"  # Tailscale UDP port for mesh networking
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Starting Tailscale daemon...'
        tailscaled --state=/var/lib/tailscale/tailscaled.state --userspace-networking &
        sleep 3
        if [ -n \"$$TS_AUTHKEY\" ]; then
          echo 'Connecting with auth key...'
          tailscale up --hostname=casaos-$${HOSTNAME:-server} --accept-routes --advertise-exit-node --auth-key=$$TS_AUTHKEY
        else
          echo 'No auth key provided - use web UI to authenticate'
        fi
        echo 'Starting web interface on :80'
        exec tailscale web --listen=0.0.0.0:80
      "

x-casaos:
  main: tailscale
  webui_port: 80
  pre-install-cmd: |
    mkdir -p /DATA/AppData/tailscale/{state,config} &&
    chown -R $PUID:$PGID /DATA/AppData/tailscale

  architectures:
    - amd64
    - arm64
  author: Yundera AppStore
  category: Network
  description:
    en_us: "Tailscale is a secure mesh VPN that creates encrypted connections between your devices. This container runs the Tailscale node daemon with web UI enabled for easy device management. Connect your CasaOS server to your Tailscale network to access it securely from anywhere. Includes exit node functionality to route traffic through your server and accept routes from other nodes. Perfect for secure remote access to your home lab and services."
  developer: Tailscale Inc.
  icon: https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Tailscale/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Tailscale/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Tailscale/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Tailscale/screenshot-3.png
  tagline:
    en_us: Zero-config mesh VPN for secure device connections
  title:
    en_us: Tailscale
  tips:
    before_install:
      en_us: |
        **🔐 Authentication Setup:**
        
        **Option 1 - Auth Key (Recommended):**
        1. Go to [Tailscale Admin Console](https://login.tailscale.com/admin/settings/keys)
        2. Generate an auth key with desired settings
        3. Set the `TS_AUTHKEY` environment variable in CasaOS before starting
        
        **Option 2 - Manual Setup:**
        1. Start the container without TS_AUTHKEY
        2. Visit the web UI at `https://tailscale-$domain/`
        3. Follow the login prompts to authenticate
        
        **📡 After Installation:**
        - Your server will appear as `casaos-[hostname]` in your Tailscale network
        - Exit node functionality is enabled by default
        - Use web UI for device management and status monitoring
        - Access other Tailscale devices using their Tailscale IPs
        
        **⚠️ Important Notes:**
        - Uses userspace networking for enhanced security
        - UDP port 41641 is exposed for mesh connectivity
        - Container runs as non-root user ($PUID:$PGID)
        - Some advanced networking features may have limitations in userspace mode