name: seafile
services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    user: 0:0
    environment:
      MYSQL_ROOT_PASSWORD: $default_pwd
      MYSQL_LOG_CONSOLE: true
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - /DATA/AppData/$AppID/mysql:/var/lib/mysql
    networks:
      - seafile-net
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect", "--mariadbupgrade", "--innodb_initialized"]
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  seafile:
    image: seafileltd/seafile-mc:12.0-latest
    container_name: seafile
    user: 0:0
    expose:
      - 80
    volumes:
      - /DATA/AppData/$AppID/data:/shared
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: seafile
      DB_ROOT_PASSWD: $default_pwd
      DB_PASSWORD: $default_pwd
      SEAFILE_MYSQL_DB_CCNET_DB_NAME: ccnet_db
      SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: seafile_db
      SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: seahub_db
      TIME_ZONE: $TZ
      INIT_SEAFILE_ADMIN_EMAIL: admin@$domain
      INIT_SEAFILE_ADMIN_PASSWORD: $default_pwd
      SEAFILE_SERVER_HOSTNAME: seafile-$domain
      SEAFILE_SERVER_PROTOCOL: https
      SITE_ROOT: /
      NON_ROOT: false
      JWT_PRIVATE_KEY: change_this_to_a_random_string_of_at_least_32_characters
      SEAFILE_LOG_TO_STDOUT: true
      ENABLE_SEADOC: false
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - seafile-net
    restart: unless-stopped

networks:
  seafile-net:
    name: seafile-net

x-casaos:
  architectures:
    - amd64
    - arm64
  main: seafile
  webui_port: 80
  author: Yundera Team
  category: Cloud
  developer: Seafile Ltd
  description:
    en_us: Seafile is an open source file sync & share solution designed for high reliability, high performance and easy scalability. Collections of files are called libraries, and each library can be synced separately. A library can be encrypted with a user chosen password. This protects the user's data privacy even if the server is compromised.
  tagline:
    en_us: Open source file sync and share platform
  title:
    en_us: Seafile
  icon: https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Seafile/icon.png
  screenshot: https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Seafile/screenshot-1.png
  thumbnail: https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Seafile/thumbnail.png
  tips:
    before_install:
      en_us: |
        Default Account
        | Username   | Password       |
        | --------   | ------------   |
        | `admin@$domain` | `$default_pwd` |
        
        Files will be stored in `/DATA/AppData/Seafile/data/`. The database will be stored in `/DATA/AppData/Seafile/mysql/`.
  index: /