name: seafile

services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    cpu_shares: 70
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$default_pwd
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /DATA/AppData/seafile/db:/var/lib/mysql
    networks:
      - seafile-network
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--mariadbupgrade",
          "--innodb_initialized",
        ]
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-alpine
    container_name: seafile-redis
    cpu_shares: 70
    deploy:
      resources:
        limits:
          memory: 128M
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=$default_pwd
    networks:
      - seafile-network

  seafile:
    image: seafileltd/seafile-mc:13.0-latest
    container_name: seafile
    hostname: seafile
    cpu_shares: 70
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - /DATA/AppData/seafile/data:/shared
      - /DATA/Media:/shared/seafile-data/library-template:ro
      - /DATA/Documents:/shared/seafile-data/documents
    environment:
      - SEAFILE_MYSQL_DB_HOST=db
      - SEAFILE_MYSQL_DB_PORT=3306
      - SEAFILE_MYSQL_DB_USER=seafile
      - SEAFILE_MYSQL_DB_PASSWORD=$default_pwd
      - INIT_SEAFILE_MYSQL_ROOT_PASSWORD=$default_pwd
      - SEAFILE_MYSQL_DB_CCNET_DB_NAME=ccnet_db
      - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=seafile_db
      - SEAFILE_MYSQL_DB_SEAHUB_DB_NAME=seahub_db
      - TIME_ZONE=$TZ
      - INIT_SEAFILE_ADMIN_EMAIL=admin@$domain
      - INIT_SEAFILE_ADMIN_PASSWORD=$default_pwd
      - SEAFILE_SERVER_HOSTNAME=seafile-$domain
      - SEAFILE_SERVER_PROTOCOL=https
      - SITE_ROOT=/
      - NON_ROOT=false  # Using root mode for simplicity
      - JWT_PRIVATE_KEY=e5Yrzk6Sibrle5Yrzk6Sibrl$default_pwd
      - SEAFILE_LOG_TO_STDOUT=false
      - ENABLE_SEADOC=false
      - CACHE_PROVIDER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=$default_pwd
      - ENABLE_NOTIFICATION_SERVER=false
      - ENABLE_SEAFILE_AI=false
      - MD_FILE_COUNT_LIMIT=100000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - seafile-network

networks:
  seafile-network:
    name: seafile-network

x-casaos:
  main: seafile
  webui_port: 80
  category: Cloud
  architectures: [amd64, arm64]
  author: Yundera Team
  developer: Seafile Ltd.
  pre-install-cmd: |
    mkdir -p /DATA/AppData/seafile/{data,db} &&
    chmod -R 755 /DATA/AppData/seafile
  title:
    en_us: Seafile
  tagline:
    en_us: Open source file sync and share solution
  icon: https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Seafile/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Seafile/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Seafile/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Worph/AppStore@main/Apps/Seafile/screenshot-3.png
  description:
    en_us: |
      **🌊 What is Seafile?**

      **Seafile** is a professional open-source file sync and share platform. Think of it as **your own private Dropbox** that you fully control.

      Unlike cloud storage services, Seafile gives you complete ownership of your data while providing enterprise-grade file synchronization, sharing, and collaboration features.

      **🔧 What Can You Do with Seafile?**

      • 📁 **File Synchronization**: Sync files across all your devices automatically
      • 🔗 **Secure Sharing**: Share files and folders with password protection and expiration dates  
      • 👥 **Team Collaboration**: Create shared libraries for team projects
      • 📱 **Mobile Access**: Access your files from iOS and Android apps
      • 🔐 **Client-Side Encryption**: Optional end-to-end encryption for sensitive data
      • 📊 **Version Control**: Keep track of file changes with automatic versioning
      • 💬 **Real-time Collaboration**: Comment and collaborate on files in real-time

      **🚀 Why Choose Seafile?**

      • **Privacy First** – Your files stay on your server, never on third-party clouds
      • **High Performance** – Optimized for large files and many concurrent users
      • **Cross-Platform** – Works on Windows, macOS, Linux, iOS, and Android
      • **Enterprise Ready** – Active Directory integration, advanced permissions, audit logs
      • **Reliable Sync** – Robust synchronization algorithm handles conflicts intelligently

      **🛠️ Perfect For:**

      • Personal file storage and sync across devices
      • Small teams needing secure file sharing
      • Organizations requiring data sovereignty
      • Anyone wanting Dropbox functionality without vendor lock-in

      **📱 Client Apps Available:**
      
      Download official Seafile clients for your devices to sync files automatically:
      • Desktop: Windows, macOS, Linux
      • Mobile: iOS App Store, Google Play Store
  tips:
    before_install:
      en_us: |
        **🚀 Quick Setup Guide**
        
        **1. First Launch:**
        
        • Initial setup may take a few minutes
        • Admin account will be created automatically
        
        **Default Credentials:**
        | Field    | Value           |
        | -------- | --------------- |
        | Email    | `admin@$domain` |
        | Password | `$default_pwd`  |
        
        **2. After Login:**
        
        • Change default admin password in settings
        • Create your first library (like a folder that syncs)
        • Download Seafile client apps for your devices
        
        **3. File Storage:**
        
        • Files stored in: `/DATA/AppData/seafile/data`
        • Media template: `/DATA/Media` (read-only access)
        • Documents: `/DATA/Documents` (full access)
        
        **4. Download Client Apps:**
        
        • Visit seafile.com to download desktop and mobile clients
        • Use your server URL to connect and sync files
  index: /