name: meetfrontend

services:           
  initializer:
    image: aptero/aptero-services-initializer:latest   # Custom initializer image
    environment:
      MAIN_DOMAIN: ${REF_DOMAIN}
      REF_DOMAIN: ${REF_DOMAIN}
      SHORTLINK_DOMAIN: "80-meetfrontend-${REF_DOMAIN}"
      RETICULUM_SERVER: "80-meetfrontend-${REF_DOMAIN}"
      API_360_TO_SCENE: "https://80-meetfrontend-${REF_DOMAIN}/service/360toscene/api/"
      NON_CORS_PROXY_DOMAINS: "80-meetfrontend-${REF_DOMAIN},digitaloceanspaces.com,wowza.com"
      CORS_PROXY_SERVER: "https://80-meetfrontend-${REF_DOMAIN}/cors"
      DEFAULT_SCENE_SID: "h8xwUAc"
      REMOTE_VM_SERVICE: "https://80-meetfrontend-${REF_DOMAIN}"
      ROOM_TOKEN_SERVICE: "https://80-meetfrontend-${REF_DOMAIN}"
      TEAMS_APP_ID: "934817ce-ddcc-48b6-9a8b-1f7ac5f654ce"
      MICROSOFT_APP_ID: "c89c5d54-37ec-49d6-952a-befc9b770079"
      MICROSOFT_APP_AUTHORITY: "https://login.microsoftonline.com/common"
      APP_SOURCE_LINK: "https://80-meetfrontend-${REF_DOMAIN}/appsource/link"
      APP_SOURCE_TEAMS_APP_LINK: "https://80-meetfrontend-${REF_DOMAIN}/teamsapplink"
      SIGNIN_REDIRECT_URI: "https://80-meetfrontend-${REF_DOMAIN}/auth-end.html"
      GLOBAL_ASSETS_PATH: "https://80-meetfrontend-${REF_DOMAIN}/data/global/"
      LOGGER_URL: "https://80-meetfrontend-${REF_DOMAIN}/tracking"
      LOGGER_ORIGIN: "meet-frontend-80-meetfrontend-${REF_DOMAIN}"
      PRIVACY_LINK: "https://80-meetfrontend-${REF_DOMAIN}/privacy.html"
      TERMS_LINK: "https://80-meetfrontend-${REF_DOMAIN}/terms.html"
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/hubconf
        target: /app/hubconf
      - type: bind
        source: /DATA/AppData/$AppID/db
        target: /var/lib/postgresql/data
    depends_on:
      - db
    x-casaos:
      hidden: true

  reverse_proxy:
    image: nginx:1.23.3
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - webtraefik
    volumes:
      - ./reverse_proxy_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse_proxy_conf/conf.d:/etc/nginx/conf.d/ 
      - ./reverse_proxy_conf/ssl/:/etc/ssl/
      - ./reverse_proxy_conf/access/:/etc/access/
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=webtraefik"
      - "traefik.frontend.rule=Host:alphahub.aptero.co"   
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.entryPoints=http,https"
    depends_on:
      - db
      - meetfrontend
      - reticulum
    x-casaos:
      hidden: true

  meetfrontend:
    hostname: meetfrontend
    image: aptero/aptero-hub:latest
    networks:
      - webtraefik
    expose:
      - "80"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/hubconf
        target: /usr/share/nginx/html/hubconf
      - /workspace/data/apterohub/data:/usr/share/nginx/html/data
      - static-web-volume:/usr/share/nginx/html/

  db:
    networks:
      - webtraefik
    hostname: db
    image: postgres:10
    command: postgres -c 'max_connections=250'
    expose:
      - "5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      #- /workspace/data/reticulum_alpha/db/:/var/lib/postgresql/data
      - type: bind
        source: /DATA/AppData/$AppID/db
        target: /var/lib/postgresql/data
    x-casaos:
      hidden: true
      
  reticulum:
    networks:
      - webtraefik
    hostname: reticulum
    image: aptero/aptero-reticulum:latest
    environment:
      - "MAIN_HOST=80-meetfrontend-${REF_DOMAIN}"
      - "NODE_ENV=production"
      - "DB_USER=postgres"
      - "DB_PWD=postgres"
      - "DB_NAME=ret_prod"
      - "DB_HOST=db"
      - "JWT_SECRET=${JWT_SECRET}"                       # User provided
      - "USER_SERVICE_URL=https://80-meetfrontend-${REF_DOMAIN}/service/dbapi"
      - "YOUTUBE_API_KEY=${YOUTUBE_API_KEY}"             # User provided
      - "UPLOAD_ENCRYPTION_KEY=${UPLOAD_ENCRYPTION_KEY}" # User provided
      - "IFRAME_SCP=https://*"
      - "SCRIPT_SRC=https://aframe.io https://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js https://s.ytimg.com https://ssl.google-analytics.com https://www.google-analytics.com https://www.youtube.com https://www.googletagmanager.com"
      - "PHOTOMNEMONIC_ENDPOINT=https://80-meetfrontend-${REF_DOMAIN}/service/photomnemonic"
      - "SMTP_HOST=mail.privateemail.com"                # User provided
      - "SMTP_PORT=465"                                  # User provided
      - "SMTP_USERNAME=${SMTP_USERNAME}"                 # User provided
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"                 # User provided
      - "PERMS_KEY=${PERMS_KEY}"                         # User provided
    volumes:
      #- /workspace/data/reticulum_alpha/storage/:/ret/storage/
      - type: bind
        source: /DATA/AppData/$AppID/reticulum/storage
        target: /ret/storage
      #- static-web-volume:/ret/storage/assets/
      - type: bind
        source: /DATA/AppData/$AppID/reticulum/assets
        target: /ret/storage/assets
    depends_on:
      - db
    x-casaos:
      hidden: true
      env: # All the User provided variables
        - JWT_SECRET
        - YOUTUBE_API_KEY
        - UPLOAD_ENCRYPTION_KEY
        - SMTP_HOST
        - SMTP_PORT
        - SMTP_USERNAME
        - SMTP_PASSWORD
        - PERMS_KEY
      env_descriptions:
        JWT_SECRET: >
          Has to be generated (script or documentation), unique per user #base 64 ALG HS512
        YOUTUBE_API_KEY: >
          Has to be generated (script or documentation), unique per user
        UPLOAD_ENCRYPTION_KEY: >
          Has to be generated (script or documentation), unique per user
        SMTP_HOST: >
          User has to fill this (with documentation)
        SMTP_PORT: >
          User has to fill this (with documentation)
        SMTP_USERNAME: >
          User has to fill this (with documentation)
        SMTP_PASSWORD: >
          User has to fill this (with documentation)
        PERMS_KEY: >
          Has to be generated (script or documentation), unique per user - RSA 2048 key
      
  spoke:
    image: aptero/aptero-spoke:latest
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - webtraefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=webtraefik"
      - "traefik.frontend.rule=Host:alphahub.aptero.co;PathPrefixStrip:/opal/"   
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.entryPoints=http,https"
    volumes:
      - ./spokeconf/properties.js:/usr/share/nginx/html/properties.js

networks:
  webtraefik:
    external: true

volumes:
  static-web-volume:

x-casaos:
  architectures:
    - amd64
    - arm64
  main: meetfrontend
  author: Aptero
  developer: Aptero
  icon: "https://github.com/krizcold/AppStore/blob/main/Apps/Aptero-Meet/icon.png?raw=true"
  tagline:
    en_us: "Custom immersive training made fast with Aptero"
  category: Productivity
  description:
    en_us: >
      Aptero Meet integrates our custom 3D platform and our web editor (Opal) to enable interactive lessons, immersive job discovery, and AI-guided training at a fraction of the cost.
  title:
    en_us: "Aptero Meet"
  index: /
  webui_port: 80
