name: qbittorrent

services:
  qbittorrent:
    user: $PUID:$PGID
    image: lscr.io/linuxserver/qbittorrent:5.1.1
    container_name: qbittorrent
    restart: unless-stopped
    expose:
      - 80
    # Uncomment the ports section if you want to expose the service on specific ports
    #ports:
    #  - 6881:6881
    #  - 6881:6881/udp
    environment:
      TZ: $TZ
      WEBUI_PORT: 80
      TORRENTING_PORT: 6881
    volumes:
      - /DATA/AppData/qbittorrent/config:/config
      - /DATA/Downloads:/downloads
    cpu_shares: 10
    deploy:
      resources:
        limits:
          memory: 512M

x-casaos:
  main: qbittorrent
  webui_port: 80
  pre-install-cmd: |
    mkdir -p /DATA/AppData/qbittorrent/config/qBittorrent &&
    docker run --rm \
      -v /DATA/AppData/qbittorrent/config/qBittorrent:/output \
      -e QB_PASSWORD="${default_pwd:-adminadmin}" \
      -e QB_USERNAME=admin \
      ghcr.io/worph/qbittorrent-config:1.0.2
  tips:
    before_install:
      en_us: |
        Login : `admin`
        Password : `$default_pwd`
        The download directory is `/DATA/Downloads`
  architectures:
    - amd64
    - arm64
  author: Yundera Team
  category: Downloader
  developer: qBittorrent Project
  description:
    en_us: qBittorrent is a cross-platform free and open-source BitTorrent client with a clean, simple interface and powerful features including sequential downloading, bandwidth scheduling, and RSS feed support.
    fr_fr: qBittorrent est un client BitTorrent multiplateforme gratuit et open-source avec une interface propre et simple et des fonctionnalités puissantes incluant le téléchargement séquentiel, la planification de bande passante et le support des flux RSS.
    es_es: qBittorrent es un cliente BitTorrent multiplataforma gratuito y de código abierto con una interfaz limpia y simple y características poderosas incluyendo descarga secuencial, programación de ancho de banda y soporte de feeds RSS.
    zh_cn: qBittorrent是一个跨平台的免费开源BitTorrent客户端，具有简洁的界面和强大的功能，包括顺序下载、带宽调度和RSS源支持。
    ko_kr: qBittorrent는 깔끔하고 간단한 인터페이스와 순차 다운로드, 대역폭 스케줄링, RSS 피드 지원을 포함한 강력한 기능을 가진 크로스 플랫폼 무료 오픈소스 BitTorrent 클라이언트입니다.
  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/qBittorrent/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/qBittorrent/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/qBittorrent/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/qBittorrent/screenshot-3.png
  index: /
  tagline:
    en_us: Powerful BitTorrent client with advanced features for managing your downloads efficiently and securely.
    fr_fr: Client BitTorrent puissant avec des fonctionnalités avancées pour gérer vos téléchargements efficacement et en sécurité.
    es_es: Potente cliente BitTorrent con características avanzadas para gestionar tus descargas de manera eficiente y segura.
    zh_cn: 功能强大的BitTorrent客户端，具有高级功能，可高效安全地管理您的下载。
    ko_kr: 다운로드를 효율적이고 안전하게 관리할 수 있는 고급 기능을 갖춘 강력한 BitTorrent 클라이언트입니다.
  title:
    en_us: qBittorrent
  store_app_id: qbittorrent
  is_uncontrolled: false