name: filebrowser
services:
  filebrowser:
    container_name: filebrowser
    user: $PUID:$PGID
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      FB_DATABASE: /db/database.db
    image: filebrowser/filebrowser:v2.32.0
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/filebrowser/db/
        target: /db/
      - type: bind
        source: /DATA
        target: /srv
    expose:
      - 80
    cpu_shares: 10
    deploy:
      resources:
        limits:
          memory: 256M
x-casaos:
  pre-install-cmd: |
    docker run --rm -v /DATA/AppData/filebrowser/db/:/db filebrowser/filebrowser config init --database /db/database.db &&
    docker run --rm -v /DATA/AppData/filebrowser/:/data ubuntu chown -R $PUID:$PGID /data &&
    docker run --rm -v /DATA/AppData/filebrowser/db/:/db filebrowser/filebrowser users add admin $default_pwd --perm.admin --database /db/database.db
  architectures:
    - amd64
    - arm64
    - arm
  main: filebrowser
  author: Yundera Team
  category: Cloud
  description:
    en_us: File Browser - Webbased File Browser including sharing functions etc.
    zh_cn: File Browser - 包含分享功能等的Webbased文件浏览器
    ar_sa: متصفح الملفات - متصفح ملفات Webbased يشمل وظائف المشاركة وما إلى ذلك
    de_de: Datei Browser - Webbasierte Datei Browser, einschließlich Sharing-Funktionen usw.
    es_es: File Browser - Navegador de archivos Webbased que incluye funciones de compartición, etc.
    fr_fr: File Browser - Navigateur de fichiers Webbased incluant des fonctions de partage, etc.
    hu_hu: File Browser - Webbased File Browser, beleértve a megosztási funkciókat stb.
    it_it: File Browser - Browser di file Webbased che include funzioni di condivisione, ecc.
    ru_ru: File Browser - Webbased File Browser, включая функции обмена, и т.д.
    pl_pl: File Browser - Przeglądarka plików Webbased, w tym funkcje udostępniania itp.
    pt_br: File Browser - Navegador de arquivos Webbased que inclui funções de compartilhamento, etc.
    sv_se: File Browser - Webbaserad filbläddrare inklusive delningsfunktioner etc.
    uk_ua: File Browser - Webbased File Browser, включаючи функції обміну, тощо
  developer: File Browser
  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/FileBrowser/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/FileBrowser/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/FileBrowser/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/FileBrowser/screenshot-3.jpg
  tagline:
    en_us: Upload, delete, preview, rename, edit and share your files.
    zh_cn: 上传，删除，预览，重命名，编辑和共享您的文件。
    ar_sa: قم بتحميل، حذف، معاينة، إعادة تسمية، تحرير ومشاركة ملفاتك.
    de_de: Hochladen, Löschen, Vorschau, Umbenennen, Bearbeiten und Freigeben Ihrer Dateien.
    es_es: Subir, eliminar, previsualizar, renombrar, editar y compartir sus archivos.
    fr_fr: Télécharger, supprimer, prévisualiser, renommer, modifier et partager vos fichiers.
    hu_hu: Töltsön fel, törölje, előnézze, átnevezze, szerkessze és ossza meg fájljait.
    it_it: Carica, elimina, anteprima, rinomina, modifica e condividi i tuoi file.
    ru_ru: Загрузите, удалите, просмотрите, переименуйте, отредактируйте и поделитесь своими файлами.
    pl_pl: Prześlij, usuń, podgląd, zmień nazwę, edytuj i udostępnij swoje pliki.
    pt_br: Faça upload, exclua, visualize, renomeie, edite e compartilhe seus arquivos.
    sv_se: Ladda upp, ta bort, förhandsgranska, byt namn, redigera och dela dina filer.
    uk_ua: Завантажте, видаліть, перегляньте, перейменуйте, відредагуйте і поділіться своїми файлами.
  thumbnail: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/FileBrowser/thumbnail.jpg
  tips:
    before_install:
      en_us: |
        Default Account
        | Username   | Password       |
        | --------   | ------------   |
        | `admin`    | `$default_pwd` |
  title:
    en_us: FileBrowser
  index: /
  webui_port: 80
