name: rocketchat

services:
  mongodb:
    image: mongo:7.0
    user: $PUID:$PGID
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 10s
      start_interval: 1s
      retries: 30
    volumes:
      - /DATA/AppData/$AppID/mongodb:/data/db

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:7.10.0
    restart: unless-stopped
    user: $PUID:$PGID
    cpu_shares: 70
    environment:
      ROOT_URL: https://rocketchat-$domain
      PORT: 80
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: compose
      MONGO_URL: mongodb://mongodb:27017/rocketchat?replicaSet=rs0
      # For future use
      INSTANCE_IP:

    expose:
      - 80
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
       test: ["CMD", "nc", "-zv", "-w", "10", "rocketchat", "80"]
       interval: 30s
       timeout: 10s
       retries: 10
       start_period: 30s

x-casaos:
  index: /
  webui_port: 80
  main: rocketchat

  icon: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/RocketChat/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/RocketChat/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/RocketChat/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/RocketChat/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/Yundera/AppStore@main/Apps/RocketChat/screenshot-1.png

  architectures:
    - amd64
    - arm64
  author: Yundera Team
  category: Communication
  description:
    en_us: Rocket.Chat 7.8.3 with marketplace enabled for team collaboration. Uses latest MongoDB 7.0 with verified replica set configuration.
    ko_kr: 마켓플레이스가 활성화된 팀 협업용 Rocket.Chat 7.8.3. 최신 MongoDB 7.0과 검증된 replica set 구성 사용.
  developer: Rocket.Chat Technologies Corp.
  tagline:
    en_us: Latest team communication with marketplace & MongoDB 7.0
    ko_kr: 마켓플레이스와 MongoDB 7.0을 지원하는 최신 팀 커뮤니케이션
  title:
    en_us: Rocket.Chat
  tips:
    before_install:
      en_us: |               
        **Privacy Settings:**
        - ❌ Statistics reporting disabled
        - ❌ Automatic updates disabled  
        - ❌ Federation disabled
        - ✅ Your data stays on your server
        
        **Setup Process:**
        1. Initial setup wizard will appear
        2. Complete email verification for marketplace access
        3. Apps marketplace will be available in admin panel
        4. Install apps like GitHub, Jira, Google Drive integrations
        
        **Jitsi Video Conferencing Setup:**
        1. Go to **Administration → Apps → Marketplace**
        2. Search for "Jitsi" and click **Install**
        3. Use `/jitsi` command in any chat to start video calls
        4. Custom room: `/jitsi @MeetingRoom`
        5. Share the generated link with participants

      ko_kr: |
        **앱 마켓플레이스가 활성화된 Rocket.Chat 7.8.3**
        
        **기본 계정**
        | 사용자명     | 비밀번호        |
        | ----------- | -------------- |
        | `admin`     | `$default_pwd` |
        
        **최신 기능 (7.8.3):**
        - ✅ 앱 마켓플레이스 (통합 앱 설치)
        - ✅ MongoDB 7.0 지원 (최신 데이터베이스)
        - ✅ Node.js 20.x 및 Meteor 3.0 성능 향상
        - ✅ 강화된 보안성과 안정성
        - ✅ Replica set 실시간 메시징
        - ✅ 팀 협업용 VoIP (베타)
        
        **프라이버시 설정:**
        - ❌ 통계 리포팅 비활성화
        - ❌ 자동 업데이트 비활성화
        - ❌ 연합 기능 비활성화
        - ✅ 데이터는 사용자 서버에만 보관
        
        **설정 과정:**
        1. 초기 설정 마법사가 나타남
        2. 마켓플레이스 접근을 위한 이메일 인증 완료
        3. 관리자 패널에서 앱 마켓플레이스 사용 가능
        4. GitHub, Jira, Google Drive 통합 등 앱 설치 가능
        
        **Jitsi 화상회의 설정:**
        1. **관리 → 앱 → 마켓플레이스**로 이동
        2. "Jitsi" 검색 후 **설치** 클릭
        3. 채팅에서 `/jitsi` 명령어로 화상통화 시작
        4. 커스텀 룸: `/jitsi @회의실`
        5. 생성된 링크를 참가자들과 공유
        
        **MongoDB 7.0 장점:**
        - 향상된 성능과 확장성
        - 강화된 보안 기능
        - 미래 지향적 데이터베이스 버전