name: wordpress

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /DATA/AppData/$AppID/wordpress:/var/www/html    
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
    depends_on:
      - db
    networks:
      pcs: null

  db:
    image: mariadb:10.6
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=wordpress
    volumes:
      - /DATA/AppData/$AppID/db:/var/lib/mysql
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  architectures:
    - amd64
    - arm64
  author: self
  category: web
  description:
    en_us: WordPress - A flexible content management system powering millions of websites worldwide, with customizable themes, plugins, and a user-friendly interface.
    zh_cn: WordPress - 一个灵活的内容管理系统，为全球数百万网站提供支持，具有可定制的主题、插件和用户友好的界面
    ko_kr: WordPress - 전 세계 수백만 개의 웹사이트를 운영하는 유연한 콘텐츠 관리 시스템으로, 맞춤형 테마, 플러그인 및 사용자 친화적인 인터페이스 제공합니다.
  icon: https://raw.githubusercontent.com/BookJJun-IJ/AppStore/create/Apps/Wordpress/icons.png
  screenshot_link:
    - https://raw.githubusercontent.com/BookJJun-IJ/AppStore/create/Apps/Wordpress/screenshots1.png
    - https://raw.githubusercontent.com/BookJJun-IJ/AppStore/create/Apps/Wordpress/screenshots2.png
    - https://raw.githubusercontent.com/BookJJun-IJ/AppStore/create/Apps/Wordpress/screenshots3.png
  index: /
  is_uncontrolled: false
  tagline:
    en_us: Create beautiful websites and blogs with ease
    zh_cn: 轻松创建精美网站和博客
    ko_kr: 아름다운 웹사이트와 블로그를 손쉽게 만들기
  port_map: "80"
  store_app_id: wordpress
  title:
    en_us: Wordpress
    zh_cn: Wordpress
    ko_kr: Wordpress
  main: wordpress
  volumes:
    - /DATA/AppData/$AppID/wordpress
    - /DATA/AppData/$AppID/db